version: '2'
services:
  mysql:
    build: ./mysql
    env_file: ./.env
    volumes:
      # 起動時に読ませたいSQLはここに置く
      - ./mysql/init:/docker-entrypoint-initdb.d
      # DBのデータそのものがここに置かれる
      - ./mysql/data:/var/lib/mysql

  phpmyadmin:
    build: ./phpmyadmin
    env_file: ./.env
    ports:
      # 8081ポートでコンテナの外に公開する
      - '8081:80'
    volumes:
      # セッション関係の自動生成ファイルが置かれる
      - ./phpmyadmin/sessions:/sessions
      # phpMyAdminのソースが置かれる
      - ./phpmyadmin/src:/var/www/html
    depends_on:
      - mysql

  app:
    build: ./app
    env_file: ./.env
    volumes:
      # PHPのソースはここに置く
      - ./app/src:/var/www/html
    depends_on:
      - mysql

  web:
    build: ./web
    env_file: ./.env
    ports:
      # 8080ポートでコンテナの外に公開する
      - '8080:80'
    depends_on:
      - app

  cron:
    build: ./cron
    env_file: ./.env
    volumes:
      - ./cron/resource/cron:/var/spool/cron
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db-data:
